package main

import (
	"library-gen/api"
	"library-gen/db"
	"library-gen/impl"
	"net/http"
	"os"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
	"github.com/joho/godotenv"
)

// Simple Auth Middleware
func AuthMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		// Public routes
		if strings.Contains(c.Request.URL.Path, "/auth/") {
			c.Next()
			return
		}

		authHeader := c.GetHeader("Authorization")
		if authHeader == "" {
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"error": "No token provided"})
			return
		}

		tokenString := strings.TrimPrefix(authHeader, "Bearer ")
		token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
			return []byte(os.Getenv("JWT_SECRET")), nil
		})

		if err != nil || !token.Valid {
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"error": "Invalid token"})
			return
		}
		c.Next()
	}
}

func main() {

	_ = godotenv.Load()
	db.Init()

	r := gin.Default()
	r.Use(AuthMiddleware())

	// Create our implementation of the interface
	server := &impl.LibraryServer{}

	// Magic happens here: This function (generated by oapi-codegen)
	// connects the Gin router to your LibraryServer methods
	// based on the openapi.yaml
	api.RegisterHandlersWithOptions(r, server, api.GinServerOptions{
		BaseURL: "/api",
	})

	r.Run(":9000")
}
