package models

import (
	"time"

	"gorm.io/gorm"
)

// We call them "Entity" to differentiate from the API types generated by OpenAPI
type BookEntity struct {
	gorm.Model
	Title  string
	Author string
	Stock  int
}

type MemberEntity struct {
	gorm.Model
	Name     string
	Email    string `gorm:"unique"`
	Password string
}

type BorrowEntity struct {
	gorm.Model
	MemberID   uint
	BookID     uint
	ReturnDate *time.Time
}
